package com.codecool.details;

public enum Privilege {
    ADD_MENTOR,
    REMOVE_MENTOR,
    EDIT_MENTOR,
    GET_ALL_MENTORS,
    GET_ALL_STUDENTS,
    ADD_ASSIGNMENT,
    GRADE_ASSIGNMENT,
    CHECK_ATTENDANCE,
    ADD_STUDENT,
    REMOVE_STUDENT,
    EDIT_STUDENT,
    SUBMIT_ASSIGNMENT,
    GET_GRADES,
    LOG_OUT,
    EXIT
}
